# Generated by Django 2.2.3 on 2019-07-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=200)),
                ('github_url', models.URLField(blank=True, max_length=100)),
                ('live_url', models.URLField(blank=True, max_length=100)),
                ('project_image', models.ImageField(blank=True, upload_to='project_images/')),
            ],
        ),
    ]
