# Generated by Django 2.2.3 on 2019-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('skills', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True, max_length=50)),
                ('github', models.URLField(blank=True, max_length=50)),
                ('facebook', models.URLField(blank=True, max_length=50)),
                ('instagram', models.URLField(blank=True, max_length=50)),
                ('twitter', models.URLField(blank=True, max_length=50)),
            ],
        ),
    ]
